// Generated by scripts/generate-vocabularies.js. Do not edit by hand.
// Source: src/vocabularies/html.js

import { element } from './core/element.js'

/**
 * The root element of an HTML document.
 * 
 * Note: when `html(...)` is used as the top-level vnode, `render()` will mount
 * into `document.documentElement` automatically.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/html
 */
export const html = element("html")

/**
 * Specifies the base URL to use for all relative URLs in a document. There can be only one such element in a document.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/base
 */
export const base = element("base")

/**
 * Contains machine-readable information (metadata) about the document, like its title, scripts, and style sheets.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/head
 */
export const head = element("head")

/**
 * Specifies relationships between the current document and an external resource. This element is most commonly used to link to CSS but is also used to establish site icons (both "favicon" style icons and icons for the home screen and apps on mobile devices) among other things.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/link
 */
export const link = element("link")

/**
 * Represents metadata that cannot be represented by other HTML meta-related elements, like <base>, <link>, <script>, <style> and <title>.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/meta
 */
export const meta = element("meta")

/**
 * Contains style information for a document or part of a document. It contains CSS, which is applied to the contents of the document containing this element.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/style
 */
export const style = element("style")

/**
 * Defines the document's title that is shown in a browser's title bar or a page's tab. It only contains text; HTML tags within the element, if any, are also treated as plain text.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/title
 */
export const title = element("title")

/**
 * Represents the content of an HTML document. There can be only one such element in a document.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/body
 */
export const body = element("body")

/**
 * Indicates that the enclosed HTML provides contact information for a person or people, or for an organization.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/address
 */
export const address = element("address")

/**
 * Represents a self-contained composition in a document, page, application, or site, which is intended to be independently distributable or reusable (e.g., in syndication). Examples include a forum post, a magazine or newspaper article, a blog entry, a product card, a user-submitted comment, an interactive widget or gadget, or any other independent item of content.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/article
 */
export const article = element("article")

/**
 * Represents a portion of a document whose content is only indirectly related to the document's main content. Asides are frequently presented as sidebars or call-out boxes.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/aside
 */
export const aside = element("aside")

/**
 * Represents a footer for its nearest ancestor sectioning content or sectioning root element. A <footer> typically contains information about the author of the section, copyright data, or links to related documents.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/footer
 */
export const footer = element("footer")

/**
 * Represents introductory content, typically a group of introductory or navigational aids. It may contain some heading elements but also a logo, a search form, an author name, and other elements.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/header
 */
export const header = element("header")

/**
 * There are six levels of section headings. <h1> is the highest section level and <h6> is the lowest.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/h1
 */
export const h1 = element("h1")

/**
 * There are six levels of section headings. <h1> is the highest section level and <h6> is the lowest.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/h2
 */
export const h2 = element("h2")

/**
 * There are six levels of section headings. <h1> is the highest section level and <h6> is the lowest.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/h3
 */
export const h3 = element("h3")

/**
 * There are six levels of section headings. <h1> is the highest section level and <h6> is the lowest.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/h4
 */
export const h4 = element("h4")

/**
 * There are six levels of section headings. <h1> is the highest section level and <h6> is the lowest.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/h5
 */
export const h5 = element("h5")

/**
 * There are six levels of section headings. <h1> is the highest section level and <h6> is the lowest.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/h6
 */
export const h6 = element("h6")

/**
 * Represents a heading grouped with any secondary content, such as subheadings, an alternative title, or a tagline.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/hgroup
 */
export const hgroup = element("hgroup")

/**
 * Represents the dominant content of the body of a document. The main content area consists of content that is directly related to or expands upon the central topic of a document, or the central functionality of an application.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/main
 */
export const main = element("main")

/**
 * Represents a section of a page whose purpose is to provide navigation links, either within the current document or to other documents. Common examples of navigation sections are menus, tables of contents, and indexes.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/nav
 */
export const nav = element("nav")

/**
 * Represents a generic standalone section of a document, which doesn't have a more specific semantic element to represent it. Sections should always have a heading, with very few exceptions.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/section
 */
export const section = element("section")

/**
 * Represents a part that contains a set of form controls or other content related to performing a search or filtering operation.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/search
 */
export const search = element("search")

/**
 * Indicates that the enclosed text is an extended quotation. Usually, this is rendered visually by indentation. A URL for the source of the quotation may be given using the cite attribute, while a text representation of the source can be given using the <cite> element.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/blockquote
 */
export const blockquote = element("blockquote")

/**
 * Provides the description, definition, or value for the preceding term (<dt>) in a description list (<dl>).
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/dd
 */
export const dd = element("dd")

/**
 * The generic container for flow content. It has no effect on the content or layout until styled in some way using CSS (e.g., styling is directly applied to it, or some kind of layout model like flexbox is applied to its parent element).
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/div
 */
export const div = element("div")

/**
 * Represents a description list. The element encloses a list of groups of terms (specified using the <dt> element) and descriptions (provided by <dd> elements). Common uses for this element are to implement a glossary or to display metadata (a list of key-value pairs).
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/dl
 */
export const dl = element("dl")

/**
 * Specifies a term in a description or definition list, and as such must be used inside a <dl> element. It is usually followed by a <dd> element; however, multiple <dt> elements in a row indicate several terms that are all defined by the immediate next <dd> element.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/dt
 */
export const dt = element("dt")

/**
 * Represents a caption or legend describing the rest of the contents of its parent <figure> element.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/figcaption
 */
export const figcaption = element("figcaption")

/**
 * Represents self-contained content, potentially with an optional caption, which is specified using the <figcaption> element. The figure, its caption, and its contents are referenced as a single unit.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/figure
 */
export const figure = element("figure")

/**
 * Represents a thematic break between paragraph-level elements: for example, a change of scene in a story, or a shift of topic within a section.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/hr
 */
export const hr = element("hr")

/**
 * Represents an item in a list. It must be contained in a parent element: an ordered list (<ol>), an unordered list (<ul>), or a menu (<menu>). In menus and unordered lists, list items are usually displayed using bullet points. In ordered lists, they are usually displayed with an ascending counter on the left, such as a number or letter.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/li
 */
export const li = element("li")

/**
 * A semantic alternative to <ul>, but treated by browsers (and exposed through the accessibility tree) as no different than <ul>. It represents an unordered list of items (which are represented by <li> elements).
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/menu
 */
export const menu = element("menu")

/**
 * Represents an ordered list of items — typically rendered as a numbered list.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/ol
 */
export const ol = element("ol")

/**
 * Represents a paragraph. Paragraphs are usually represented in visual media as blocks of text separated from adjacent blocks by blank lines and/or first-line indentation, but HTML paragraphs can be any structural grouping of related content, such as images or form fields.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/p
 */
export const p = element("p")

/**
 * ')
 * Represents preformatted text which is to be presented exactly as written in the HTML file. The text is typically rendered using a non-proportional, or monospaced, font. Whitespace inside this element is displayed as written.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/pre
 */
export const pre = element("pre")

/**
 * Represents an unordered list of items, typically rendered as a bulleted list.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/ul
 */
export const ul = element("ul")

/**
 * Together with its href attribute, creates a hyperlink to web pages, files, email addresses, locations within the current page, or anything else a URL can address.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/a
 */
export const a = element("a")

/**
 * Represents an abbreviation or acronym.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/abbr
 */
export const abbr = element("abbr")

/**
 * Used to draw the reader's attention to the element's contents, which are not otherwise granted special importance. This was formerly known as the Boldface element, and most browsers still draw the text in boldface. However, you should not use <b> for styling text or granting importance. If you wish to create boldface text, you should use the CSS font-weight property. If you wish to indicate an element is of special importance, you should use the <strong> element.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/b
 */
export const b = element("b")

/**
 * Tells the browser's bidirectional algorithm to treat the text it contains in isolation from its surrounding text. It's particularly useful when a website dynamically inserts some text and doesn't know the directionality of the text being inserted.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/bdi
 */
export const bdi = element("bdi")

/**
 * Overrides the current directionality of text, so that the text within is rendered in a different direction.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/bdo
 */
export const bdo = element("bdo")

/**
 * Produces a line break in text (carriage-return). It is useful for writing a poem or an address, where the division of lines is significant.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/br
 */
export const br = element("br")

/**
 * Used to mark up the title of a creative work. The reference may be in an abbreviated form according to context-appropriate conventions related to citation metadata.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/cite
 */
export const cite = element("cite")

/**
 * Displays its contents styled in a fashion intended to indicate that the text is a short fragment of computer code. By default, the content text is displayed using the user agent's default monospace font.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/code
 */
export const code = element("code")

/**
 * Links a given piece of content with a machine-readable translation. If the content is time- or date-related, the <time> element must be used.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/data
 */
export const data = element("data")

/**
 * Used to indicate the term being defined within the context of a definition phrase or sentence. The ancestor <p> element, the <dt>/<dd> pairing, or the nearest section ancestor of the <dfn> element, is considered to be the definition of the term.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/dfn
 */
export const dfn = element("dfn")

/**
 * Marks text that has stress emphasis. The <em> element can be nested, with each nesting level indicating a greater degree of emphasis.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/em
 */
export const em = element("em")

/**
 * Represents a range of text that is set off from the normal text for some reason, such as idiomatic text, technical terms, and taxonomical designations, among others. Historically, these have been presented using italicized type, which is the original source of the <i> naming of this element.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/i
 */
export const i = element("i")

/**
 * Represents a span of inline text denoting textual user input from a keyboard, voice input, or any other text entry device. By convention, the user agent defaults to rendering the contents of a <kbd> element using its default monospace font, although this is not mandated by the HTML standard.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/kbd
 */
export const kbd = element("kbd")

/**
 * Represents text which is marked or highlighted for reference or notation purposes due to the marked passage's relevance in the enclosing context.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/mark
 */
export const mark = element("mark")

/**
 * Indicates that the enclosed text is a short inline quotation. Most modern browsers implement this by surrounding the text in quotation marks. This element is intended for short quotations that don't require paragraph breaks; for long quotations use the <blockquote> element.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/q>
 */
export const q = element("q")

/**
 * Used to provide fall-back parentheses for browsers that do not support the display of ruby annotations using the <ruby> element. One <rp> element should enclose each of the opening and closing parentheses that wrap the <rt> element that contains the annotation's text.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/rp
 */
export const rp = element("rp")

/**
 * Specifies the ruby text component of a ruby annotation, which is used to provide pronunciation, translation, or transliteration information for East Asian typography. The <rt> element must always be contained within a <ruby> element.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/rt
 */
export const rt = element("rt")

/**
 * Represents small annotations that are rendered above, below, or next to base text, usually used for showing the pronunciation of East Asian characters. It can also be used for annotating other kinds of text, but this usage is less common.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/ruby
 */
export const ruby = element("ruby")

/**
 * Renders text with a strikethrough, or a line through it. Use the <s> element to represent things that are no longer relevant or no longer accurate. However, <s> is not appropriate when indicating document edits; for that, use the <del> and <ins> elements, as appropriate.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/s
 */
export const s = element("s")

/**
 * Used to enclose inline text which represents sample (or quoted) output from a computer program. Its contents are typically rendered using the browser's default monospaced font (such as Courier or Lucida Console).
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/samp
 */
export const samp = element("samp")

/**
 * Represents side-comments and small print, like copyright and legal text, independent of its styled presentation. By default, it renders text within it one font size smaller, such as from small to x-small.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/small
 */
export const small = element("small")

/**
 * A generic inline container for phrasing content, which does not inherently represent anything. It can be used to group elements for styling purposes (using the class or id attributes), or because they share attribute values, such as lang. It should be used only when no other semantic element is appropriate. <span> is very much like a div element, but div is a block-level element whereas a <span> is an inline-level element.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/span
 */
export const span = element("span")

/**
 * Indicates that its contents have strong importance, seriousness, or urgency. Browsers typically render the contents in bold type.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/strong
 */
export const strong = element("strong")

/**
 * Specifies inline text which should be displayed as subscript for solely typographical reasons. Subscripts are typically rendered with a lowered baseline using smaller text.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/sub
 */
export const sub = element("sub")

/**
 * Specifies inline text which is to be displayed as superscript for solely typographical reasons. Superscripts are usually rendered with a raised baseline using smaller text.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/sup
 */
export const sup = element("sup")

/**
 * Represents a specific period in time. It may include the datetime attribute to translate dates into machine-readable format, allowing for better search engine results or custom features such as reminders.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/time
 */
export const time = element("time")

/**
 * Represents a span of inline text which should be rendered in a way that indicates that it has a non-textual annotation. This is rendered by default as a single solid underline but may be altered using CSS.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/u
 */
export const u = element("u")

/**
 * Represents the name of a variable in a mathematical expression or a programming context. It's typically presented using an italicized version of the current typeface, although that behavior is browser-dependent.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/var
 */
export const htmlvar = element("var")

/**
 * Represents a word break opportunity—a position within text where the browser may optionally break a line, though its line-breaking rules would not otherwise create a break at that location.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/wbr
 */
export const wbr = element("wbr")

/**
 * Defines an area inside an image map that has predefined clickable areas. An image map allows geometric areas on an image to be associated with hyperlink.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/area
 */
export const area = element("area")

/**
 * Used to embed sound content in documents. It may contain one or more audio sources, represented using the src attribute or the source element: the browser will choose the most suitable one. It can also be the destination for streamed media, using a MediaStream.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
 */
export const audio = element("audio")

/**
 * Embeds an image into the document.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
 */
export const img = element("img")

/**
 * Used with <area> elements to define an image map (a clickable link area).
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/map
 */
export const map = element("map")

/**
 * Used as a child of the media elements, audio and video. It lets you specify timed text tracks (or time-based data), for example to automatically handle subtitles. The tracks are formatted in WebVTT format (.vtt files)—Web Video Text Tracks.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/track
 */
export const track = element("track")

/**
 * Embeds a media player which supports video playback into the document. You can also use <video> for audio content, but the audio element may provide a more appropriate user experience.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/video
 */
export const video = element("video")

/**
 * Embeds external content at the specified point in the document. This content is provided by an external application or other source of interactive content such as a browser plug-in.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/embed
 */
export const embed = element("embed")

/**
 * Represents a nested browsing context, embedding another HTML page into the current one.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/iframe
 */
export const iframe = element("iframe")

/**
 * Represents an external resource, which can be treated as an image, a nested browsing context, or a resource to be handled by a plugin.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/object
 */
export const object = element("object")

/**
 * Contains zero or more <source> elements and one <img> element to offer alternative versions of an image for different display/device scenarios.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/picture
 */
export const picture = element("picture")

/**
 * Specifies multiple media resources for the picture, the audio element, or the video element. It is a void element, meaning that it has no content and does not have a closing tag. It is commonly used to offer the same media content in multiple file formats in order to provide compatibility with a broad range of browsers given their differing support for image file formats and media file formats.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/source
 */
export const source = element("source")

/**
 * Container element to use with either the canvas scripting API or the WebGL API to draw graphics and animations.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/canvas
 */
export const canvas = element("canvas")

/**
 * Defines a section of HTML to be inserted if a script type on the page is unsupported or if scripting is currently turned off in the browser.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/noscript
 */
export const noscript = element("noscript")

/**
 * Used to embed executable code or data; this is typically used to embed or refer to JavaScript code. The <script> element can also be used with other languages, such as WebGL's GLSL shader programming language and JSON.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/script
 */
export const script = element("script")

/**
 * Represents a range of text that has been deleted from a document. This can be used when rendering "track changes" or source code diff information, for example. The <ins> element can be used for the opposite purpose: to indicate text that has been added to the document.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/del
 */
export const del = element("del")

/**
 * Represents a range of text that has been added to a document. You can use the <del> element to similarly represent a range of text that has been deleted from the document.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/ins
 */
export const ins = element("ins")

/**
 * Specifies the caption (or title) of a table.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/caption
 */
export const caption = element("caption")

/**
 * Defines one or more columns in a column group represented by its implicit or explicit parent <colgroup> element. The <col> element is only valid as a child of a <colgroup> element that has no span attribute defined.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/col
 */
export const col = element("col")

/**
 * Defines a group of columns within a table.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/colgroup
 */
export const colgroup = element("colgroup")

/**
 * Represents tabular data—that is, information presented in a two-dimensional table comprised of rows and columns of cells containing data.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/table
 */
export const table = element("table")

/**
 * Encapsulates a set of table rows (<tr> elements), indicating that they comprise the body of a table's (main) data.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/tbody
 */
export const tbody = element("tbody")

/**
 * A child of the <tr> element, it defines a cell of a table that contains data.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/td
 */
export const td = element("td")

/**
 * Encapsulates a set of table rows (<tr> elements), indicating that they comprise the foot of a table with information about the table's columns. This is usually a summary of the columns, e.g., a sum of the given numbers in a column.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/tfoot
 */
export const tfoot = element("tfoot")

/**
 * A child of the <tr> element, it defines a cell as the header of a group of table cells. The nature of this group can be explicitly defined by the scope and headers attributes.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/th
 */
export const th = element("th")

/**
 * Encapsulates a set of table rows (<tr> elements), indicating that they comprise the head of a table with information about the table's columns. This is usually in the form of column headers (<th> elements).
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/thead
 */
export const thead = element("thead")

/**
 * Defines a row of cells in a table. The row's cells can then be established using a mix of <td> (data cell) and <th> (header cell) elements.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/tr
 */
export const tr = element("tr")

/**
 * An interactive element activated by a user with a mouse, keyboard, finger, voice command, or other assistive technology. Once activated, it performs an action, such as submitting a form or opening a dialog.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button
 */
export const button = element("button")

/**
 * Contains a set of <option> elements that represent the permissible or recommended options available to choose from within other controls.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/datalist
 */
export const datalist = element("datalist")

/**
 * Used to group several controls as well as labels (<label>) within a web form.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/fieldset
 */
export const fieldset = element("fieldset")

/**
 * Represents a document section containing interactive controls for submitting information.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/form
 */
export const form = element("form")

/**
 * Used to create interactive controls for web-based forms to accept data from the user; a wide variety of types of input data and control widgets are available, depending on the device and user agent. The <input> element is one of the most powerful and complex in all of HTML due to the sheer number of combinations of input types and attributes.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/input
 */
export const input = element("input")

/**
 * Represents a caption for an item in a user interface.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/label
 */
export const label = element("label")

/**
 * Represents a caption for the content of its parent <fieldset>.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/legend
 */
export const legend = element("legend")

/**
 * Represents either a scalar value within a known range or a fractional value.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/meter
 */
export const meter = element("meter")

/**
 * Creates a grouping of options within a <select> element.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/optgroup
 */
export const optgroup = element("optgroup")

/**
 * Used to define an item contained in a select, an <optgroup>, or a <datalist> element. As such, <option> can represent menu items in popups and other lists of items in an HTML document.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/option
 */
export const option = element("option")

/**
 * Container element into which a site or app can inject the results of a calculation or the outcome of a user action.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/output
 */
export const output = element("output")

/**
 * Displays an indicator showing the completion progress of a task, typically displayed as a progress bar.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/progress
 */
export const progress = element("progress")

/**
 * Represents a control that provides a menu of options.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/select
 */
export const select = element("select")

/**
 * Represents a multi-line plain-text editing control, useful when you want to allow users to enter a sizeable amount of free-form text, for example, a comment on a review or feedback form.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/textarea
 */
export const textarea = element("textarea")

/**
 * Creates a disclosure widget in which information is visible only when the widget is toggled into an "open" state. A summary or label must be provided using the <summary> element.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/details
 */
export const details = element("details")

/**
 * Represents a dialog box or other interactive component, such as a dismissible alert, inspector, or subwindow.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/dialog
 */
export const dialog = element("dialog")

/**
 * Specifies a summary, caption, or legend for a details element's disclosure box. Clicking the <summary> element toggles the state of the parent <details> element open and closed.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/summary
 */
export const summary = element("summary")

/**
 * Part of the Web Components technology suite, this element is a placeholder inside a web component that you can fill with your own markup, which lets you create separate DOM trees and present them together.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/slot
 */
export const slot = element("slot")

/**
 * A mechanism for holding HTML that is not to be rendered immediately when a page is loaded but may be instantiated subsequently during runtime using JavaScript.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/template
 */
export const template = element("template")

/**
 * An ancient and poorly supported precursor to the <img> element. It should not be used.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/image
 */
export const image = element("image")

/**
 * Used to delimit the base text component of a ruby annotation, i.e., the text that is being annotated. One <rb> element should wrap each separate atomic segment of the base text.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/rb
 */
export const rb = element("rb")

/**
 * Embraces semantic annotations of characters presented in a ruby of <rb> elements used inside of <ruby> element. <rb> elements can have both pronunciation (<rt>) and semantic (<rtc>) annotations.
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/rtc
 */
export const rtc = element("rtc")
