// Generated by scripts/generate-vocabularies.js. Do not edit by hand.
// Source: src/vocabularies/mathml.js

import { element } from './core/element.js'

/**
 * The root element of a MathML expression.
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/math
 */
export const math = element("math")

/**
 * Groups sub-expressions without introducing visible separators.
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mrow
 */
export const mrow = element("mrow")

/**
 * Identifier (variable/function name).
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mi
 */
export const mi = element("mi")

/**
 * Operator (e.g. "+", "→", parentheses).
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mo
 */
export const mo = element("mo")

/**
 * Number literal.
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mn
 */
export const mn = element("mn")

/**
 * Text inside math layout.
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mtext
 */
export const mtext = element("mtext")

/**
 * Spacing control.
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mspace
 */
export const mspace = element("mspace")

/**
 * Styling wrapper for MathML subtree.
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mstyle
 */
export const mstyle = element("mstyle")

/**
 * Encloses content (e.g. boxes, circles).
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/menclose
 */
export const menclose = element("menclose")

/**
 * Convenience fencing wrapper (parentheses, brackets).
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mfenced
 */
export const mfenced = element("mfenced")

/**
 * Superscript.
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/msup
 */
export const msup = element("msup")

/**
 * Subscript.
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/msub
 */
export const msub = element("msub")

/**
 * Subscript + superscript.
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/msubsup
 */
export const msubsup = element("msubsup")

/**
 * Fraction.
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mfrac
 */
export const mfrac = element("mfrac")

/**
 * Square root.
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/msqrt
 */
export const msqrt = element("msqrt")

/**
 * Root with explicit index.
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mroot
 */
export const mroot = element("mroot")

/**
 * Under-script.
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/munder
 */
export const munder = element("munder")

/**
 * Over-script.
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mover
 */
export const mover = element("mover")

/**
 * Under + over script.
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/munderover
 */
export const munderover = element("munderover")

/**
 * Table layout.
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mtable
 */
export const mtable = element("mtable")

/**
 * Table row.
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mtr
 */
export const mtr = element("mtr")

/**
 * Table cell.
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mtd
 */
export const mtd = element("mtd")

/**
 * Attach semantic annotations to a presentation tree.
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/semantics
 */
export const semantics = element("semantics")

/**
 * A textual annotation inside <semantics>.
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/annotation
 */
export const annotation = element("annotation")

/**
 * An XML annotation inside <semantics>.
 * 
 * Exported as `annotationXml` because of the dash in the tag name.
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/annotation-xml
 */
export const annotationXml = element("annotation-xml")

/**
 * Content MathML application node: first child is the operator, remaining
 * children are arguments.
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/apply
 */
export const apply = element("apply")

/**
 * Content MathML identifier.
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/ci
 */
export const ci = element("ci")

/**
 * Content MathML number.
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/cn
 */
export const cn = element("cn")

/**
 * Content MathML symbol (often with a content dictionary via `cd`).
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/csymbol
 */
export const csymbol = element("csymbol")

/**
 * Content MathML binding node (e.g. lambda).
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/bind
 */
export const bind = element("bind")

/**
 * Bound variable (used under <bind>).
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/bvar
 */
export const bvar = element("bvar")

/**
 * Lambda binder operator (typically inside <bind>).
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/lambda
 */
export const lambda = element("lambda")

/**
 * Content MathML set constructor (often under <apply>).
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/set
 */
export const set = element("set")

/**
 * Content MathML list constructor (often under <apply>).
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/list
 */
export const list = element("list")

/**
 * Content MathML vector constructor.
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/vector
 */
export const vector = element("vector")

/**
 * Content MathML matrix constructor.
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/matrix
 */
export const matrix = element("matrix")

/**
 * Content MathML matrix row.
 * https://developer.mozilla.org/en-US/docs/Web/MathML/Element/matrixrow
 */
export const matrixrow = element("matrixrow")
