import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const scriptDir = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(scriptDir, '..')

const readText = filePath =>
  fs.readFileSync(filePath, 'utf8')

const writeTextIfChanged = (filePath, next) => {
  const prev = fs.existsSync(filePath) ? readText(filePath) : null
  if (prev === next) return false
  fs.writeFileSync(filePath, next)
  return true
}

const between = (text, begin, end) => {
  const start = text.indexOf(begin)
  if (start === -1) throw new Error(`Missing marker: ${begin}`)

  const stop = text.indexOf(end, start + begin.length)
  if (stop === -1) throw new Error(`Missing marker: ${end}`)

  return text.slice(start + begin.length, stop)
}

const findTagline = text => {
  const line = text.match(/^###\s+(.+)$/m)?.[1]?.trim()
  return line || null
}

const toPosix = filePath => filePath.split(path.sep).join('/')

const toGithubUrl = (repoRelativePath, { dir }) => {
  const kind = dir ? 'tree' : 'blob'
  return `https://github.com/pfernandez/elements/${kind}/main/${toPosix(repoRelativePath)}`
}

const rewriteRepoRelativeLinks = (md, { root }) =>
  md.replaceAll(/\]\((\.\/[^)]+)\)/g, (m, href) => {
    const rel = href.slice(2)
    const fullPath = path.resolve(root, rel)
    if (!fs.existsSync(fullPath)) return m
    const dir = fs.statSync(fullPath).isDirectory()
    return `](${toGithubUrl(rel, { dir })})`
  })

const buildElementsPackageReadme = rootReadme => {
  const begin = '<!-- BEGIN README:elements -->'
  const end = '<!-- END README:elements -->'

  const tagline = findTagline(rootReadme)
  const body = between(rootReadme, begin, end).trim()

  return [
    '<!-- Generated by scripts/sync-readmes.js. Source: README.md -->',
    '',
    '# @pfern/elements',
    '',
    ...(tagline ? [tagline, ''] : []),
    body,
    ''
  ].join('\n')
}

const main = () => {
  const rootReadmePath = path.join(repoRoot, 'README.md')
  const elementsReadmePath = path.join(repoRoot, 'packages/elements/README.md')

  const rootReadme = readText(rootReadmePath)
  const pkgReadme =
    rewriteRepoRelativeLinks(
      buildElementsPackageReadme(rootReadme),
      { root: repoRoot }
    )

  const changed = writeTextIfChanged(elementsReadmePath, pkgReadme)
  changed && console.log(`updated: ${path.relative(repoRoot, elementsReadmePath)}`)
}

main()

